/**
 * ═══════════════════════════════════════════════════════════
 * TDS ENGINE – Business-Type-Aware Realistic TDS Generator
 *
 * Rules:
 *  • Retail / Trading / Electronics / Grocery / Mobile:
 *      → 194H (payment gateway settlement)   – primary
 *      → 194C (courier / transport)          – secondary (turnover > ₹15L)
 *      → 194N ONLY if turnover > ₹2 crore   – rare
 *      → 194NF NOT generated by default
 *
 *  • Other Services / Professional:
 *      → 194H (platform commission)          – primary
 *      → 194J (professional fee received)    – secondary
 *      → 194C if logistics involved
 *
 * Every figure is mathematically derived from turnover.
 * ═══════════════════════════════════════════════════════════
 */

const TDSEngine = (() => {

  // ── Business type classifier ───────────────────────────────
  const RETAIL_TYPES    = ['Mobile Retail','Retail Trade','General Trading','Electronics','Grocery','Others'];
  const SERVICE_TYPES   = ['Other Services'];

  // ── Default TDS rates (% of turnover) ─────────────────────
  const DEFAULTS = {
    retail194H_rate:   0.0015,   // 0.15% of turnover
    retail194C_rate:   0.00035,  // 0.035% of turnover
    service194H_rate:  0.0010,   // 0.10% of turnover
    service194J_rate:  0.0020,   // 0.20% of turnover (professional fee TDS)
    min194C_turnover:  1500000,  // 194C only if turnover > ₹15L
    min194N_turnover:  20000000, // 194N only if turnover > ₹2 crore
  };

  /**
   * Generate realistic TDS based on turnover and business type.
   *
   * @param {number} turnover        Annual turnover
   * @param {string} natureOfBiz     Nature of business (from dropdown)
   * @param {Object} adminConfig     Admin-configured overrides
   * @param {Array}  banks           Bank accounts (for deductor names)
   * @returns {Object}               { tds194H, tds194C, tds194N, tds194J, totalTDS, entries }
   */
  /**
   * Generate realistic TDS based on turnover, business type, and presumptive section.
   *
   * @param {number} turnover            Annual turnover
   * @param {string} natureOfBiz         Nature of business (from dropdown)
   * @param {Object} adminConfig         Admin-configured overrides
   * @param {Array}  banks               Bank accounts (for deductor names)
   * @param {string} ay                  Assessment Year (e.g. '2026-27')
   * @param {string} presumptiveSection  '44AD' | '44ADA' | 'none'
   * @returns {Object}                   { tds194H, tds194C, tds194N, tds194J, totalTDS, entries }
   */
  function generate(turnover, natureOfBiz, adminConfig = {}, banks = [], ay = '2026-27', presumptiveSection = '44AD') {
    // Sanitise turnover – must be a valid non-negative number
    turnover = Math.max(0, parseFloat(turnover) || 0);

    const is44ADA   = presumptiveSection === '44ADA';
    const is44AD    = presumptiveSection === '44AD';
    const isRetail  = !natureOfBiz || RETAIL_TYPES.includes(natureOfBiz);
    const isService = SERVICE_TYPES.includes(natureOfBiz) || is44ADA;
    const selectedDeductors = adminConfig.selectedDeductors || [];

    // Apply admin rate overrides (rates stored as plain %, e.g. 0.20 means 0.20%)
    const r194H = (adminConfig.rate194H != null && adminConfig.rate194H > 0)
      ? (adminConfig.rate194H / 100)
      : (isRetail ? DEFAULTS.retail194H_rate : DEFAULTS.service194H_rate);
    const r194C = (adminConfig.rate194C != null && adminConfig.rate194C > 0)
      ? (adminConfig.rate194C / 100)
      : DEFAULTS.retail194C_rate;
    const r194J = DEFAULTS.service194J_rate;

    let tds194H = 0, tds194C = 0, tds194N = 0, tds194J = 0;
    let entries = [];

    // ── MANUAL DEDUCTOR MODE: When specific deductor(s) are selected by user ──
    if (selectedDeductors && selectedDeductors.length > 0) {
      // Calculate realistic aggregate TDS base for the business turnover
      const baseRate = isService ? 0.0020 : 0.0015;
      const calculatedTds = Math.round(turnover * baseRate);
      const targetTotal = turnover > 0 ? Math.max(500, _roundRealistic(calculatedTds)) : 0;

      if (targetTotal > 0) {
        const count = selectedDeductors.length;
        const shares = _distributeAmounts(targetTotal, count);
        const dates = _fakeDates(count, ay);

        selectedDeductors.forEach((ded, i) => {
          let amt = shares[i] || Math.max(100, Math.round(targetTotal / count));

          const cat = (ded.category || '').toLowerCase();
          const name = (ded.name || '').toUpperCase();
          let section = '194C';
          let grossBase = 0;

          if (cat.includes('gateway') || name.includes('RAZORPAY') || name.includes('PAYTM') || name.includes('PHONEPE')) {
            section = '194H';
            grossBase = Math.round(amt / 0.05); // 5% / 2% commission base
            tds194H += amt;
          } else if (cat.includes('logistics') || name.includes('DELHIVERY') || name.includes('BLUEDART') || name.includes('EKART')) {
            section = '194C';
            grossBase = Math.round(amt / 0.02); // 2% contractor base
            tds194C += amt;
          } else if (cat.includes('bank') || name.includes('BANK')) {
            section = turnover >= DEFAULTS.min194N_turnover ? '194N' : '194C';
            grossBase = section === '194N' ? Math.round(amt / 0.02) + 2000000 : Math.round(amt / 0.02);
            if (section === '194N') tds194N += amt; else tds194C += amt;
          } else if (is44ADA || cat.includes('professional') || cat.includes('service')) {
            section = '194J';
            grossBase = Math.round(amt / 0.10); // 10% professional fee base
            tds194J += amt;
          } else {
            section = isRetail ? '194C' : '194J';
            grossBase = section === '194J' ? Math.round(amt / 0.10) : Math.round(amt / 0.02);
            if (section === '194J') tds194J += amt; else tds194C += amt;
          }

          entries.push({
            section,
            deductorName: (ded.name || `DEDUCTOR ${i + 1}`).toUpperCase(),
            deductorTAN:  ded.tan || _fakeTAN(section.slice(-1)),
            dateOfCredit: dates[i] || _fakeDate(ay),
            amountPaid:   grossBase,
            tdsClaimed:   amt,
            tdsDeposited: amt,
          });
        });
      }

      // Final NaN guard
      tds194H = Math.max(0, tds194H || 0);
      tds194C = Math.max(0, tds194C || 0);
      tds194N = Math.max(0, tds194N || 0);
      tds194J = Math.max(0, tds194J || 0);
      const totalTDS = tds194H + tds194C + tds194N + tds194J;

      return { tds194H, tds194C, tds194N, tds194J, totalTDS, entries };
    }

    // ── AUTO DEDUCTOR MODE: Dynamic Simulation ──
    // 194H: Commission / Brokerage
    if (!is44AD && !is44ADA && turnover > 0) {
      const digitalBase = Math.round(turnover * 0.60);
      tds194H = _roundRealistic(Math.round(digitalBase * r194H));
    }

    // 194C: Courier / Transport / Contractor
    if (turnover >= DEFAULTS.min194C_turnover || is44AD) {
      const logisticsBase = Math.round(turnover * 0.08);
      tds194C = _roundRealistic(Math.round(logisticsBase * r194C));
    }

    // 194J: Professional Fee
    if ((is44ADA || (isService && !is44AD)) && turnover > 0) {
      tds194J = _roundRealistic(Math.round(turnover * r194J));
    }

    // 194N: Cash Withdrawal (only large turnovers)
    if (turnover >= DEFAULTS.min194N_turnover) {
      const cashWithdrawal = Math.round(turnover * 0.03);
      const excessCash     = Math.max(0, cashWithdrawal - 2000000);
      if (excessCash > 0) {
        tds194N = _roundRealistic(Math.round(excessCash * 0.02));
      }
    }

    // Final NaN guard
    tds194H = Math.max(0, tds194H || 0);
    tds194C = Math.max(0, tds194C || 0);
    tds194N = Math.max(0, tds194N || 0);
    tds194J = Math.max(0, tds194J || 0);

    const totalTDS = tds194H + tds194C + tds194N + tds194J;

    entries = _buildEntries({
      tds194H, tds194C, tds194N, tds194J,
      banks, turnover, isRetail, isService, is44ADA, ay,
      selectedDeductors: [],
    });

    return { tds194H, tds194C, tds194N, tds194J, totalTDS, entries };
  }

  /**
   * Build individual deductor entries for 26AS-style display.
   */
  function _buildEntries({ tds194H, tds194C, tds194N, tds194J, banks, turnover, isRetail, isService, is44ADA, ay, selectedDeductors }) {
    const entries = [];
    const primaryBank = banks.find(b => b.primary) || banks[0] || {};

    // 194H: Split across 1–2 payment gateway deductors
    if (tds194H > 0) {
      const parts = _split194H(tds194H);
      const names = ['RAZORPAY PAYMENTS PVT LTD', 'PAYTM PAYMENTS BANK LTD', 'PHONEPE PRIVATE LIMITED'];
      const commissionRate = 0.002; // 0.2% commission rate
      parts.forEach((amt, i) => {
        if (amt <= 0) return;
        entries.push({
          section:      '194H',
          deductorName: names[i] || `PAYMENT GATEWAY ${i + 1}`,
          deductorTAN:  _fakeTAN('R'),
          dateOfCredit: _fakeDate(ay),
          amountPaid:   Math.round(amt / commissionRate),
          tdsClaimed:   amt,
          tdsDeposited: amt,
        });
      });
    }

    // 194C: Logistics/courier deductor
    if (tds194C > 0) {
      const logisticsNames = ['DELHIVERY LIMITED', 'BLUEDART EXPRESS LIMITED', 'EKART LOGISTICS PVT LTD'];
      entries.push({
        section:      '194C',
        deductorName: logisticsNames[Math.floor(Math.random() * logisticsNames.length)],
        deductorTAN:  _fakeTAN('D'),
        dateOfCredit: _fakeDate(ay),
        amountPaid:   Math.round(tds194C / 0.02),
        tdsClaimed:   tds194C,
        tdsDeposited: tds194C,
      });
    }

    // 194J: Professional fee (Section 44ADA / Services)
    if (tds194J > 0) {
      entries.push({
        section:      '194J',
        deductorName: 'CLIENT / PRINCIPAL COMPANY',
        deductorTAN:  _fakeTAN('C'),
        dateOfCredit: _fakeDate(ay),
        amountPaid:   Math.round(tds194J / 0.10), // 194J rate is 10%
        tdsClaimed:   tds194J,
        tdsDeposited: tds194J,
      });
    }

    // 194N: Bank cash withdrawal (only large cases)
    if (tds194N > 0) {
      const rawBankName  = (primaryBank.name || 'AXIS BANK').toUpperCase();
      const deductorName = rawBankName.includes('LIMITED') ? rawBankName : rawBankName + ' LIMITED';
      entries.push({
        section:      '194N',
        deductorName: deductorName,
        deductorTAN:  _fakeTAN('B'),
        dateOfCredit: _fakeDate(ay),
        amountPaid:   Math.round(tds194N / 0.02) + 2000000,
        tdsClaimed:   tds194N,
        tdsDeposited: tds194N,
      });
    }

    // Apply selected deductors overrides if provided
    if (selectedDeductors && selectedDeductors.length > 0) {
      let deductorIndex = 0;
      entries.forEach(entry => {
        if (entry.section !== '194N') {
          const deductor = selectedDeductors[deductorIndex % selectedDeductors.length];
          if (deductor) {
            entry.deductorName = deductor.name || entry.deductorName;
            entry.deductorTAN  = deductor.tan  || _fakeTAN('O');
          }
          deductorIndex++;
        }
      });
    }

    return entries;
  }

  /** Split 194H amount across 2 deductors with realistic proportions */
  function _split194H(total) {
    if (total <= 500) return [total];
    const ratio = 0.55 + (Math.random() * 0.20);
    const first = _roundRealistic(Math.round(total * ratio));
    const second = total - first;
    return second > 0 ? [first, second] : [total];
  }

  /**
   * Round to a "realistic" human-looking figure.
   * e.g. 8217 → 8200  |  1543 → 1550  |  342 → 340
   */
  function _roundRealistic(n) {
    if (!n || isNaN(n) || n <= 0) return 0;
    if (n < 200)    return Math.round(n / 10)   * 10;
    if (n < 1000)   return Math.round(n / 50)   * 50;
    if (n < 10000)  return Math.round(n / 100)  * 100;
    if (n < 100000) return Math.round(n / 500)  * 500;
    return Math.round(n / 1000) * 1000;
  }

  /** Generate a plausible TAN string */
  function _fakeTAN(typeChar = 'D') {
    const cities = ['DEL', 'MUM', 'CHE', 'BAN', 'HYD', 'KOL', 'PUN'];
    const city   = cities[Math.floor(Math.random() * cities.length)];
    const chars  = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ';
    const r      = () => chars[Math.floor(Math.random() * 26)];
    const d      = () => Math.floor(Math.random() * 10);
    return `${city}${typeChar}${d()}${d()}${d()}${d()}${r()}`;
  }

  /**
   * Generate a plausible credit date strictly within the Financial Year (FY = AY - 1).
   * For AY 2026-27, the FY is 2025-26 (01/04/2025 to 31/03/2026).
   */
  function _fakeDate(ay = '2026-27') {
    let ayYear = 2026;
    if (typeof ay === 'string' && ay.includes('-')) {
      const parsed = parseInt(ay.split('-')[0], 10);
      if (!isNaN(parsed) && parsed > 2000) ayYear = parsed;
    } else if (typeof ay === 'number') {
      ayYear = ay;
    }

    // Financial Year is the 12 months preceding the Assessment Year
    const fyStart = ayYear - 1; // e.g. 2025 for AY 2026-27
    const fyEnd   = ayYear;     // e.g. 2026 for AY 2026-27

    const months = [4, 5, 6, 7, 8, 9, 10, 11, 12, 1, 2, 3];
    const m = months[Math.floor(Math.random() * months.length)];
    const maxDays = (m === 2) ? 28 : ([4, 6, 9, 11].includes(m) ? 30 : 31);
    const d = Math.floor(Math.random() * maxDays) + 1;
    const y = m >= 4 ? fyStart : fyEnd;

    return `${String(d).padStart(2, '0')}/${String(m).padStart(2, '0')}/${y}`;
  }

  /**
   * Distribute total amount into realistic, naturally varied, non-identical chunks
   */
  function _distributeAmounts(total, count) {
    if (count <= 1) return [total];

    // Generate distinct random weights with natural variation (e.g. 35%, 28%, 22%, 15%)
    const rawWeights = [];
    for (let i = 0; i < count; i++) {
      rawWeights.push(0.5 + Math.random() * 1.0);
    }
    const sumW = rawWeights.reduce((s, w) => s + w, 0);
    const normalized = rawWeights.map(w => w / sumW);

    const parts = [];
    let allocated = 0;

    for (let i = 0; i < count - 1; i++) {
      let share = Math.round(total * normalized[i]);
      share = _roundRealistic(share);
      if (share <= 0) share = Math.max(50, Math.round(total / (count * 2)));
      parts.push(share);
      allocated += share;
    }

    let last = total - allocated;
    if (last <= 0 || (count > 2 && last > total * 0.6)) {
      last = Math.max(100, _roundRealistic(Math.round(total * normalized[count - 1])));
    }
    parts.push(last);

    // Ensure no identical amounts between any deductors
    for (let i = 0; i < parts.length; i++) {
      for (let j = i + 1; j < parts.length; j++) {
        if (parts[i] === parts[j]) {
          const delta = parts[j] >= 1000 ? (50 * (j + 1)) : (20 * (j + 1));
          parts[j] += delta;
        }
      }
    }

    return parts;
  }

  /**
   * Generate multiple distinct credit dates spread across the financial year
   */
  function _fakeDates(count, ay = '2026-27') {
    let ayYear = 2026;
    if (typeof ay === 'string' && ay.includes('-')) {
      const parsed = parseInt(ay.split('-')[0], 10);
      if (!isNaN(parsed) && parsed > 2000) ayYear = parsed;
    } else if (typeof ay === 'number') {
      ayYear = ay;
    }

    const fyStart = ayYear - 1;
    const fyEnd   = ayYear;
    const months = [4, 5, 6, 7, 8, 9, 10, 11, 12, 1, 2, 3];
    const shuffled = [...months].sort(() => Math.random() - 0.5);
    const dates = [];

    for (let i = 0; i < count; i++) {
      const m = shuffled[i % shuffled.length];
      const maxDays = (m === 2) ? 28 : ([4, 6, 9, 11].includes(m) ? 30 : 31);
      const d = Math.floor(Math.random() * (maxDays - 3)) + 1;
      const y = m >= 4 ? fyStart : fyEnd;
      dates.push(`${String(d).padStart(2, '0')}/${String(m).padStart(2, '0')}/${y}`);
    }

    return dates;
  }

  return { generate, _roundRealistic, _fakeDate, _distributeAmounts, _fakeDates };
})();
