/**
 * ═══════════════════════════════════════════════════════════
 * TDS ENGINE – Business-Type-Aware Realistic TDS Generator
 *
 * Rules:
 *  • Retail / Trading / Electronics / Grocery / Mobile:
 *      → 194H (payment gateway settlement)   – primary
 *      → 194C (courier / transport)          – secondary (turnover > ₹15L)
 *      → 194N ONLY if turnover > ₹2 crore   – rare
 *      → 194NF NOT generated by default
 *
 *  • Other Services / Professional:
 *      → 194H (platform commission)          – primary
 *      → 194J (professional fee received)    – secondary
 *      → 194C if logistics involved
 *
 * Every figure is mathematically derived from turnover.
 * ═══════════════════════════════════════════════════════════
 */

const TDSEngine = (() => {

  // ── Business type classifier ───────────────────────────────
  const RETAIL_TYPES    = ['Mobile Retail','Retail Trade','General Trading','Electronics','Grocery','Others'];
  const SERVICE_TYPES   = ['Other Services'];

  // ── Default TDS rates (% of turnover) ─────────────────────
  const DEFAULTS = {
    retail194H_rate:   0.0015,   // 0.15% of turnover
    retail194C_rate:   0.00035,  // 0.035% of turnover
    service194H_rate:  0.0010,   // 0.10% of turnover
    service194J_rate:  0.0020,   // 0.20% of turnover (professional fee TDS)
    min194C_turnover:  1500000,  // 194C only if turnover > ₹15L
    min194N_turnover:  20000000, // 194N only if turnover > ₹2 crore
  };

  /**
   * Generate realistic TDS based on turnover and business type.
   *
   * @param {number} turnover        Annual turnover
   * @param {string} natureOfBiz     Nature of business (from dropdown)
   * @param {Object} adminConfig     Admin-configured overrides
   * @param {Array}  banks           Bank accounts (for deductor names)
   * @returns {Object}               { tds194H, tds194C, tds194N, tds194J, totalTDS, entries }
   */
  /**
   * Generate realistic TDS based on turnover, business type, and presumptive section.
   *
   * @param {number} turnover            Annual turnover
   * @param {string} natureOfBiz         Nature of business (from dropdown)
   * @param {Object} adminConfig         Admin-configured overrides
   * @param {Array}  banks               Bank accounts (for deductor names)
   * @param {string} ay                  Assessment Year (e.g. '2026-27')
   * @param {string} presumptiveSection  '44AD' | '44ADA' | 'none'
   * @returns {Object}                   { tds194H, tds194C, tds194N, tds194J, totalTDS, entries }
   */
  function generate(turnover, natureOfBiz, adminConfig = {}, banks = [], ay = '2026-27', presumptiveSection = '44AD') {
    // Sanitise turnover – must be a valid non-negative number
    turnover = Math.max(0, parseFloat(turnover) || 0);

    const is44ADA   = presumptiveSection === '44ADA';
    const is44AD    = presumptiveSection === '44AD';
    const isRetail  = !natureOfBiz || RETAIL_TYPES.includes(natureOfBiz);
    const isService = SERVICE_TYPES.includes(natureOfBiz) || is44ADA;

    // Apply admin rate overrides (rates stored as plain %, e.g. 0.20 means 0.20%)
    const r194H = (adminConfig.rate194H != null && adminConfig.rate194H > 0)
      ? (adminConfig.rate194H / 100)
      : (isRetail ? DEFAULTS.retail194H_rate : DEFAULTS.service194H_rate);
    const r194C = (adminConfig.rate194C != null && adminConfig.rate194C > 0)
      ? (adminConfig.rate194C / 100)
      : DEFAULTS.retail194C_rate;
    const r194J = DEFAULTS.service194J_rate;

    let tds194H = 0, tds194C = 0, tds194N = 0, tds194J = 0;

    // ── 194H: Commission / Brokerage ────────────────────────
    // Note: Section 44AD(6) prohibits 44AD for Commission/Brokerage income.
    // Therefore, 194H is only generated if NOT under Section 44AD/44ADA or explicitly overridden.
    if (!is44AD && !is44ADA && turnover > 0) {
      const digitalBase = Math.round(turnover * 0.60);
      tds194H = _roundRealistic(Math.round(digitalBase * r194H));
    }

    // ── 194C: Courier / Transport / Contractor ───────────────
    // Meaningful if turnover crosses ₹15L threshold or under 44AD trade/logistics
    if (turnover >= DEFAULTS.min194C_turnover || is44AD) {
      const logisticsBase = Math.round(turnover * 0.08); // ~8% of turnover is freight/contract
      tds194C = _roundRealistic(Math.round(logisticsBase * r194C));
    }

    // ── 194J: Professional Fee (Section 44ADA / Services) ────
    // Generated for 44ADA (Professionals) or service businesses not under 44AD
    if ((is44ADA || (isService && !is44AD)) && turnover > 0) {
      tds194J = _roundRealistic(Math.round(turnover * r194J));
    }

    // ── 194N: Cash Withdrawal (only large turnovers) ─────────
    if (turnover >= DEFAULTS.min194N_turnover) {
      const cashWithdrawal = Math.round(turnover * 0.03);
      const excessCash     = Math.max(0, cashWithdrawal - 2000000); // above ₹20L
      if (excessCash > 0) {
        tds194N = _roundRealistic(Math.round(excessCash * 0.02));
      }
    }

    // Final NaN guard – all TDS values must be non-negative integers
    tds194H = Math.max(0, tds194H || 0);
    tds194C = Math.max(0, tds194C || 0);
    tds194N = Math.max(0, tds194N || 0);
    tds194J = Math.max(0, tds194J || 0);

    const totalTDS = tds194H + tds194C + tds194N + tds194J;

    // ── Generate deductor entries (26AS format) ──────────────
    const entries = _buildEntries({
      tds194H, tds194C, tds194N, tds194J,
      banks, turnover, isRetail, isService, is44ADA, ay,
      selectedDeductors: adminConfig.selectedDeductors || [],
    });

    return { tds194H, tds194C, tds194N, tds194J, totalTDS, entries };
  }

  /**
   * Build individual deductor entries for 26AS-style display.
   */
  function _buildEntries({ tds194H, tds194C, tds194N, tds194J, banks, turnover, isRetail, isService, is44ADA, ay, selectedDeductors }) {
    const entries = [];
    const primaryBank = banks.find(b => b.primary) || banks[0] || {};

    // 194H: Split across 1–2 payment gateway deductors
    if (tds194H > 0) {
      const parts = _split194H(tds194H);
      const names = ['RAZORPAY PAYMENTS PVT LTD', 'PAYTM PAYMENTS BANK LTD', 'PHONEPE PRIVATE LIMITED'];
      const commissionRate = 0.002; // 0.2% commission rate
      parts.forEach((amt, i) => {
        if (amt <= 0) return;
        entries.push({
          section:      '194H',
          deductorName: names[i] || `PAYMENT GATEWAY ${i + 1}`,
          deductorTAN:  _fakeTAN('R'),
          dateOfCredit: _fakeDate(ay),
          amountPaid:   Math.round(amt / commissionRate),
          tdsClaimed:   amt,
          tdsDeposited: amt,
        });
      });
    }

    // 194C: Logistics/courier deductor
    if (tds194C > 0) {
      const logisticsNames = ['DELHIVERY LIMITED', 'BLUEDART EXPRESS LIMITED', 'EKART LOGISTICS PVT LTD'];
      entries.push({
        section:      '194C',
        deductorName: logisticsNames[Math.floor(Math.random() * logisticsNames.length)],
        deductorTAN:  _fakeTAN('D'),
        dateOfCredit: _fakeDate(ay),
        amountPaid:   Math.round(tds194C / 0.02),
        tdsClaimed:   tds194C,
        tdsDeposited: tds194C,
      });
    }

    // 194J: Professional fee (Section 44ADA / Services)
    if (tds194J > 0) {
      entries.push({
        section:      '194J',
        deductorName: 'CLIENT / PRINCIPAL COMPANY',
        deductorTAN:  _fakeTAN('C'),
        dateOfCredit: _fakeDate(ay),
        amountPaid:   Math.round(tds194J / 0.10), // 194J rate is 10%
        tdsClaimed:   tds194J,
        tdsDeposited: tds194J,
      });
    }

    // 194N: Bank cash withdrawal (only large cases)
    if (tds194N > 0) {
      const rawBankName  = (primaryBank.name || 'AXIS BANK').toUpperCase();
      const deductorName = rawBankName.includes('LIMITED') ? rawBankName : rawBankName + ' LIMITED';
      entries.push({
        section:      '194N',
        deductorName: deductorName,
        deductorTAN:  _fakeTAN('B'),
        dateOfCredit: _fakeDate(ay),
        amountPaid:   Math.round(tds194N / 0.02) + 2000000,
        tdsClaimed:   tds194N,
        tdsDeposited: tds194N,
      });
    }

    // Apply selected deductors overrides if provided
    if (selectedDeductors && selectedDeductors.length > 0) {
      let deductorIndex = 0;
      entries.forEach(entry => {
        if (entry.section !== '194N') {
          const deductor = selectedDeductors[deductorIndex % selectedDeductors.length];
          if (deductor) {
            entry.deductorName = deductor.name || entry.deductorName;
            entry.deductorTAN  = deductor.tan  || _fakeTAN('O');
          }
          deductorIndex++;
        }
      });
    }

    return entries;
  }

  /** Split 194H amount across 2 deductors with realistic proportions */
  function _split194H(total) {
    if (total <= 500) return [total];
    const ratio = 0.55 + (Math.random() * 0.20);
    const first = _roundRealistic(Math.round(total * ratio));
    const second = total - first;
    return second > 0 ? [first, second] : [total];
  }

  /**
   * Round to a "realistic" human-looking figure.
   * e.g. 8217 → 8200  |  1543 → 1550  |  342 → 340
   */
  function _roundRealistic(n) {
    if (!n || isNaN(n) || n <= 0) return 0;
    if (n < 200)    return Math.round(n / 10)   * 10;
    if (n < 1000)   return Math.round(n / 50)   * 50;
    if (n < 10000)  return Math.round(n / 100)  * 100;
    if (n < 100000) return Math.round(n / 500)  * 500;
    return Math.round(n / 1000) * 1000;
  }

  /** Generate a plausible TAN string */
  function _fakeTAN(typeChar = 'D') {
    const cities = ['DEL', 'MUM', 'CHE', 'BAN', 'HYD', 'KOL', 'PUN'];
    const city   = cities[Math.floor(Math.random() * cities.length)];
    const chars  = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ';
    const r      = () => chars[Math.floor(Math.random() * 26)];
    const d      = () => Math.floor(Math.random() * 10);
    return `${city}${typeChar}${d()}${d()}${d()}${d()}${r()}`;
  }

  /**
   * Generate a plausible credit date strictly within the Financial Year (FY = AY - 1).
   * For AY 2026-27, the FY is 2025-26 (01/04/2025 to 31/03/2026).
   */
  function _fakeDate(ay = '2026-27') {
    let ayYear = 2026;
    if (typeof ay === 'string' && ay.includes('-')) {
      const parsed = parseInt(ay.split('-')[0], 10);
      if (!isNaN(parsed) && parsed > 2000) ayYear = parsed;
    } else if (typeof ay === 'number') {
      ayYear = ay;
    }

    // Financial Year is the 12 months preceding the Assessment Year
    const fyStart = ayYear - 1; // e.g. 2025 for AY 2026-27
    const fyEnd   = ayYear;     // e.g. 2026 for AY 2026-27

    const months = [4, 5, 6, 7, 8, 9, 10, 11, 12, 1, 2, 3];
    const m = months[Math.floor(Math.random() * months.length)];
    const maxDays = (m === 2) ? 28 : ([4, 6, 9, 11].includes(m) ? 30 : 31);
    const d = Math.floor(Math.random() * maxDays) + 1;
    const y = m >= 4 ? fyStart : fyEnd;

    return `${String(d).padStart(2, '0')}/${String(m).padStart(2, '0')}/${y}`;
  }

  return { generate, _roundRealistic, _fakeDate };
})();
